// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIlV1mJmh-oSSRvfUHBHuHDPD3An07Iw',
    appId: '1:21354824236:web:ae3ac5173579fb6c7a8789',
    messagingSenderId: '21354824236',
    projectId: 'rolex-emp',
    authDomain: 'rolex-emp.firebaseapp.com',
    storageBucket: 'rolex-emp.appspot.com',
    measurementId: 'G-70BGG0WXE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudRvqjX1kWsXMwAfiRbY6B8CT1ikHoeQ',
    appId: '1:21354824236:android:c40e123f6b0cf7677a8789',
    messagingSenderId: '21354824236',
    projectId: 'rolex-emp',
    storageBucket: 'rolex-emp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41tKOdViB9SYEw6kyxGobc6gsG6OOWbU',
    appId: '1:21354824236:ios:4c706cea38c3c9f77a8789',
    messagingSenderId: '21354824236',
    projectId: 'rolex-emp',
    storageBucket: 'rolex-emp.appspot.com',
    iosBundleId: 'com.dev.rolexemp.rolexEmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD41tKOdViB9SYEw6kyxGobc6gsG6OOWbU',
    appId: '1:21354824236:ios:4c706cea38c3c9f77a8789',
    messagingSenderId: '21354824236',
    projectId: 'rolex-emp',
    storageBucket: 'rolex-emp.appspot.com',
    iosBundleId: 'com.dev.rolexemp.rolexEmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwIlV1mJmh-oSSRvfUHBHuHDPD3An07Iw',
    appId: '1:21354824236:web:c8f134a4d3084b427a8789',
    messagingSenderId: '21354824236',
    projectId: 'rolex-emp',
    authDomain: 'rolex-emp.firebaseapp.com',
    storageBucket: 'rolex-emp.appspot.com',
    measurementId: 'G-DZSN1LT6EG',
  );
}
